// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLWjZh1zYBUJ_F4Td7--WAn85bImgAUjk',
    appId: '1:474933792377:web:cb61f68c9aa38e00154ea8',
    messagingSenderId: '474933792377',
    projectId: 'kit305-607-4543b',
    authDomain: 'kit305-607-4543b.firebaseapp.com',
    storageBucket: 'kit305-607-4543b.appspot.com',
    measurementId: 'G-9HH91P53HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXm2tmqLRGPAc7xbBP_vqNlK5WaBsSHk',
    appId: '1:474933792377:android:4f9c5abbc01ddda6154ea8',
    messagingSenderId: '474933792377',
    projectId: 'kit305-607-4543b',
    storageBucket: 'kit305-607-4543b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh43cAHHEES0lrLzIKLDFBm3_NFQFCJik',
    appId: '1:474933792377:ios:038bccdf47669cdd154ea8',
    messagingSenderId: '474933792377',
    projectId: 'kit305-607-4543b',
    storageBucket: 'kit305-607-4543b.appspot.com',
    iosClientId: '474933792377-q3thbgf467jcdifiapgvmt2cutj16dl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.babytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh43cAHHEES0lrLzIKLDFBm3_NFQFCJik',
    appId: '1:474933792377:ios:038bccdf47669cdd154ea8',
    messagingSenderId: '474933792377',
    projectId: 'kit305-607-4543b',
    storageBucket: 'kit305-607-4543b.appspot.com',
    iosClientId: '474933792377-q3thbgf467jcdifiapgvmt2cutj16dl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.babytracker',
  );
}
